name: radiohub-docs push Docker

on:
  push:
    branches:
    - master

jobs:

  radiohub-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 👀
      uses: actions/checkout@v1

    - name: Setup Google Cloud Auth 🔑
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_IAM_LAB_EMAIL }}
        service_account_key: ${{ secrets.GCP_IAM_LAB_KEY }}
        
    - name: Login to Registry 🔑
      run: "gcloud auth configure-docker"

    - name: Building docker image 🚧
      run: docker build ./ --file ./Dockerfile -t swr-radiohub-docs

    - name: Tagging docker 🏷
      run: docker tag swr-radiohub-docs eu.gcr.io/swr-lab/swr-radiohub-docs:git-$(date +%j)-$(date +%H)$(date +%M)

    - name: Pushing docker 🙇
      run: docker push eu.gcr.io/swr-lab/swr-radiohub-docs:git-$(date +%j)-$(date +%H)$(date +%M)

    - name: Logout 👋
      run: docker logout
