name: radiohub-docs push


on:
  push:
    branches:
    - master


env:
  IMAGE_NAME: swr-radiohub-docs


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 👀
      uses: actions/checkout@v2.3.1

    - name: Setup Google Cloud Auth 🔑
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_IAM_LAB_EMAIL }}
        service_account_key: ${{ secrets.GCP_IAM_LAB_KEY }}
        
    - name: Login to Registry 🔑
      run: "gcloud auth configure-docker"

    - name: Building docker image 🚧
      run: docker build ./ --file ./Dockerfile -t image

    - name: Set Cloud Run environment
      run: "gcloud config set run/platform managed"

    - name: Set Cloud Run region
      run: "gcloud config set run/region europe-west1"

    - name: Tagging & Pushing docker 🏷
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        
        docker tag image eu.gcr.io/swr-lab/$IMAGE_NAME:git-$(date +%j)-$VERSION-$GITHUB_SHA
        docker push eu.gcr.io/swr-lab/$IMAGE_NAME:git-$(date +%j)-$VERSION-$GITHUB_SHA
  
        gcloud run deploy $IMAGE_NAME --image eu.gcr.io/swr-lab/$IMAGE_NAME:git-$(date +%j)-$VERSION-$GITHUB_SHA --project swr-lab

    - name: Logout 👋
      run: docker logout
